### ISSUE TITLE
constructor内でのsyncは危険では？

### ISSUE THREAD

**Issue by okunishinishi** [FujiHaruka/kv-file-cache#1]
constructor内で`mkdirp.sync(this.cacheDir)`しているが、これを知らずにnew しまくるとprocess全体が待たされるので地味な嫌がらせとなる。

`set()`の中で、mkdirpをawait したほうが良さそう

**Comment by FujiHaruka** [comment]
https://github.com/FujiHaruka/kv-file-cache/commit/7bec99ca1f1d896dbcea0ccdbc79b8099801d98e closes this issue.
